/*
Every kind of file fuji knows, keyed by extension, and the one place any part of fuji learns what it can do with one. The folder listing keeps only what is named here, the sheet's flow chooses how to draw a thumbnail by it, the store types a blob from it, associate.js offers these to the operating system, and the settings show them in the words below.

The table is the complete list fuji grows into rather than a list that grows. An entry can be here, with its history, before fuji can do anything with it, and fileTypesEnabled below is the entries switched on, which is what the listing, the flow and the registration read. Today the ten pictures are on and everything else waits; an entry that is off records what fuji intends for it, and its platform lists get checked against the code on the day it is switched on. The settings alone read the whole table, to show the waiting entries under a heading of their own, coming soon, which is the one place fuji does anything with them.

An entry never says what category it is in. Its properties are parts of fuji, each listing the platforms where that part can handle the format, since a short video can be as much a thumbnail as a GIF is, and what can draw a file differs from one operating system to the next. The first entry's comments say what each property is, and the first video and the first audio entry introduce theirs. imageNative is short on purpose rather than a guess at what a machine could manage: Windows for JPEG and PNG alone, though WIC at the factory reads BMP, GIF and a few more; the Mac for the formats fuji has run ImageIO against and watched decode; and never Linux, which has no native route. Every picture that is on lists all three platforms under imageWeb, which is what fuji has always assumed, written down now where a later entry can say otherwise. Where both can make a thumbnail the flow prefers imageNative, a contactSheet of img wins over both so a GIF animates even where the operating system could make a still of it, and a file nothing on this platform can draw gets the placeholder, and a chip once there is one. Some of the oldest pictures have no route on any platform, and the decoder that reads them is FFmpeg, which arrives with libmpv, so that question waits for video.

A type names the extension rather than the format on purpose, since a shared type would scatter a folder's .jpe files through the only sort by extension Explorer has. A title names what the format can do and never what it cannot, in one order, lossless or vector, then transparency, then animation, leaving out what the format allows but people rarely use, like animation in PNG, SVG and AVIF. Audio is the medium, beside image and video, so a title and a property say audio; sound is what a video has and what an audio file holds, so the prose says a video is with sound and a WAV holds Windows' sounds.

This file imports nothing, so it sits beneath everything that reads it. Two lists live outside it and change with it in the same commit, because each is read where this file cannot reach. CFBundleDocumentTypes in src-tauri/Info.plist declares the enabled extensions to the Mac, which reads it out of the bundle before any of fuji's code has run; generating it from this table was declined while the table changed about once a year, which is worth deciding again as it grows. And sniff in src-tauri/src/thumbnail.rs knows each format by its first bytes, the wall a file passes before any decoder sees it, so a format given a thumbnail route needs a signature there.

The table runs far past what fuji plays because it is a manifest of what is out there. Fuji is a love letter to the years personal computers learned to show color and then to play video, and to the collections people made once they could: pictures pulled down from a BBS at 2400 baud, clips off a CD-ROM, songs from Napster, and on through the forums, imageboards, Reddit and Discord that keep the same habit today. Picture the homebrew computer club of that first multimedia decade meeting again, with every hard drive its members have ever owned. What sits on those drives, from then to now, is what this table names, and no more: a format a collector would have to look up is the long tail, and it stays out.

So each entry's about names where a format started and reads that forward to today: the year it arrived, who made it and for which machine, what people used it for and traded it as, and where it stands now. That is what tells a reader why their folder looks the way it does and what to expect of a file in it, in a few sentences that never repeat what the title already says the format can do.
*/

export const fileTypes = {
	'.bmp': {
		enabled: true,//fuji lists, draws, offers and shows this extension; false keeps an entry here, described and waiting, and out of sight everywhere else
		mime: 'image/bmp',//what the store types a blob as; after the slash, the format the flow checks against the file's first bytes
		type: 'BMP Image',//what Windows prints in Explorer's Type column once fuji opens the extension
		title: 'Lossless image',//the first line of the extension's card in fuji's settings
		imageNative: ['mac'],//platforms where Rust asks the operating system for a still picture of the file, ImageIO on the Mac and WIC on Windows; Windows is left out though WIC reads BMP, since fuji keeps its native route on Windows to JPEG and PNG
		imageWeb: ['mac', 'windows', 'linux'],//platforms where the web renderer draws the file in an img
		contactSheet: 'canvas',//how the contact sheet shows it: canvas, a thumbnail fuji sized; img, a live img that animates or stays vector; or chip, the extension alone in a box
		about: `Windows' own bitmap, from its first versions in the 1980s, in the form most files have used since Windows 3.0 in 1990. It stores every pixel as it is, usually with no compression at all, which makes it simple for any program to read and very large on disk. It was everywhere in the 1990s, as wallpaper, Paint pictures and screenshots, and never took hold on the web. Today it mostly comes from old software and scanners.`,//the card's few sentences of history
	},
	'.dib': {
		enabled: false,
		mime: 'image/bmp',
		type: 'DIB Image',
		title: 'Lossless image',
		imageNative: [],//a BMP inside, but neither ImageIO nor WIC is asked by this name; to be checked
		imageWeb: ['mac', 'windows', 'linux'],//the store types the blob as a BMP and the engine decodes it as one
		contactSheet: 'canvas',
		about: `Windows' device-independent bitmap, the name Windows 3.0 gave the same picture in 1990, for one that could travel between displays without the driver's help. A few of Windows' own tools and some others wrote the name, rarely, and inside it is a BMP, sometimes without the short file header a .bmp starts with. Most programs that open .bmp open it once they recognize the name.`,
	},
	'.gif': {
		enabled: true,
		mime: 'image/gif',
		type: 'GIF Image',
		title: 'Image with transparency and animation',
		imageNative: [],//empty though ImageIO and WIC both read GIF, because the sheet always shows a GIF live so it animates, and a still would never be used; a GIF is usually small, so the web renderer drawing it whole costs little
		imageWeb: ['mac', 'windows', 'linux'],
		contactSheet: 'img',
		about: `CompuServe's Graphics Interchange Format, 1987, with animation added in 1989. Every browser has shown it ever since, which made it the web's first logos and "under construction" signs, and later its reaction loops. Its limits show: 256 colors per frame, transparency that is all or nothing, and large files for anything like video. A patent on its compression is why PNG was invented, in 1996.`,
	},
	'.jpg': {
		enabled: true,
		mime: 'image/jpeg',
		type: 'JPG Image',
		title: 'Image',
		imageNative: ['mac', 'windows'],
		imageWeb: ['mac', 'windows', 'linux'],
		contactSheet: 'canvas',
		about: `JPEG, the Joint Photographic Experts Group's standard of 1992, in its most common spelling: three letters, to fit the file names of DOS and early Windows. It made photographs small enough for the disks, modems and web of the 1990s by discarding detail the eye barely notices, and cameras still write it today. The discarding shows around sharp edges and text, and again each time a picture is edited and saved, and it holds no transparency.`,
	},
	'.jpeg': {
		enabled: true,
		mime: 'image/jpeg',
		type: 'JPEG Image',
		title: 'Image',
		imageNative: ['mac', 'windows'],
		imageWeb: ['mac', 'windows', 'linux'],
		contactSheet: 'canvas',
		about: `The full four-letter spelling of JPEG, the 1992 standard for photographs. Systems without DOS's three-letter limit, like the Mac and Unix, often used it, and some web tools and phones still do. Inside it is the same as a .jpg in every way: a small photograph, made by discarding detail the eye barely notices, which shows around sharp edges and text.`,
	},
	'.jpe': {
		enabled: true,
		mime: 'image/jpeg',
		type: 'JPE Image',
		title: 'Image',
		imageNative: ['mac', 'windows'],
		imageWeb: ['mac', 'windows', 'linux'],
		contactSheet: 'canvas',
		about: `An uncommon three-letter spelling of JPEG, the 1992 standard for photographs, which some older programs wrote. Inside it is an ordinary JPEG, the same as a .jpg: a small photograph, made by discarding detail the eye barely notices. Few programs write it now, though most still open it.`,
	},
	'.jfif': {
		enabled: true,
		mime: 'image/jpeg',
		type: 'JFIF Image',
		title: 'Image',
		imageNative: ['mac', 'windows'],
		imageWeb: ['mac', 'windows', 'linux'],
		contactSheet: 'canvas',
		about: `The JPEG File Interchange Format, the 1992 layout that almost every JPEG follows inside, whatever it is called. As an extension it was rare until around 2019, when a setting in Windows began pointing web browsers at .jfif as the extension for a JPEG, and pictures saved from the web started arriving with it. Inside it is an ordinary JPEG, though a program that does not know the name may not offer to open it.`,
	},
	'.png': {
		enabled: true,
		mime: 'image/png',
		type: 'PNG Image',
		title: 'Lossless image with transparency',
		imageNative: ['mac', 'windows'],
		imageWeb: ['mac', 'windows', 'linux'],
		contactSheet: 'canvas',
		about: `Portable Network Graphics, 1996, made by volunteers as a free replacement for GIF once GIF's compression patent began to be enforced. It is lossless, so every pixel comes back exactly as it was saved, and it holds millions of colors and smooth transparency. That makes it the format of screenshots, logos, icons and interface graphics, though a photograph saved as PNG comes out many times larger than as JPEG.`,
	},
	'.svg': {
		enabled: true,
		mime: 'image/svg+xml',
		type: 'SVG Image',
		title: 'Vector image with transparency',
		imageNative: [],//empty because neither ImageIO nor WIC reads SVG; the sheet shows it live, so it stays sharp at any size, and inside an img a script in the file never runs
		imageWeb: ['mac', 'windows', 'linux'],
		contactSheet: 'img',
		about: `Scalable Vector Graphics, a W3C standard from 2001. Rather than pixels it holds shapes, lines and text, written out as XML, so it stays sharp at any size and is often tiny. Browsers were slow to take it up, and it became common for icons, logos, charts and diagrams once Internet Explorer 9 joined the others in 2011. It suits nothing photographic.`,
	},
	'.avif': {
		enabled: true,
		mime: 'image/avif',
		type: 'AVIF Image',
		title: 'Image with transparency',
		imageNative: ['mac'],//not Windows: WIC reads AVIF only with an extension from the Microsoft Store, which a machine may not have, and the web renderer always can
		imageWeb: ['mac', 'windows', 'linux'],//the one entry where the every-picture-everywhere assumption is known to bend: WebKit gained AVIF in 2022, so a Mac on an older system shows the placeholder
		contactSheet: 'canvas',
		about: `The AV1 Image File Format, 2019, from the Alliance for Open Media, the group of Google, Netflix, Mozilla and others behind the AV1 video codec. A picture is a single frame of AV1, far smaller than a JPEG of the same quality, with room for high dynamic range, wide color and transparency. Browsers added it between 2020 and 2022, and image services on the web now send it widely. It is slow to make, and older software still cannot open it.`,
	},
	'.webp': {
		enabled: true,
		mime: 'image/webp',
		type: 'WebP Image',//WebP keeps its own capitals, being the one format whose name is not simply its letters
		title: 'Image with transparency and animation',
		imageNative: ['mac'],//not Windows: WIC reads WebP only with an extension from the Microsoft Store, which a machine may not have, and the web renderer always can
		imageWeb: ['mac', 'windows', 'linux'],
		contactSheet: 'canvas',
		about: `Google's image format of 2010, built from the VP8 video codec it had bought, and later given lossless pictures, transparency and animation. Its pictures are about a quarter to a third smaller than JPEG or PNG, and Google pushed it across the web. For years few programs besides Chrome could show it, so a picture saved from a web page often would not open anywhere else; every major browser has had it since Safari added it in 2020.`,
	},
	'.pcx': {
		enabled: false,
		mime: 'image/x-pcx',
		type: 'PCX Image',
		title: 'Lossless image',
		imageNative: [],//neither ImageIO nor WIC reads it; the route would be FFmpeg, through libmpv, which does
		imageWeb: [],//no browser has ever shown it
		contactSheet: 'chip',//until a route exists
		about: `ZSoft's PC Paintbrush format, 1985, and the picture format of DOS. Paintbrush shipped with Windows 3.0 and wrote it, scanners and clip art collections came in it, and games of the early 1990s kept their screens and artwork in it, so it is common among files kept from that decade. It holds 256 colors from a palette, compressed lightly, and by Windows 95 BMP, GIF and JPEG had taken its places. Photoshop and the shareware viewers still open it; little else does.`,
	},
	'.tga': {
		enabled: false,
		mime: 'image/x-tga',
		type: 'TGA Image',
		title: 'Lossless image with transparency',
		imageNative: ['mac'],//ImageIO is believed to read Targa, to be checked; WIC does not
		imageWeb: [],
		contactSheet: 'canvas',
		about: `Truevision's Targa, 1984, made for the video capture cards of the same name, so it held true color and a transparency channel years before most formats. That made it the file of 3D rendering and video work through the 1990s, and of game textures and screenshots after, and 3D tools still write it. It is simple, usually uncompressed and large, and no browser shows it.`,
	},
	'.tif': {
		enabled: false,
		mime: 'image/tiff',
		type: 'TIF Image',
		title: 'Lossless image with transparency',
		imageNative: ['mac', 'windows'],//ImageIO and WIC both read it at the factory
		imageWeb: ['mac'],//Safari alone shows a TIFF in an img, and always has; Chromium never
		contactSheet: 'canvas',
		about: `The Tagged Image File Format, Aldus, 1986, and Adobe's since 1994, in the three-letter spelling DOS needed. It is the format of scanners, fax, desktop publishing and print, lossless as a rule and often enormous. Inside it is a set of tags rather than one layout, so a file can hold several pages, layers, or a compression another program never learned, and not every TIFF opens everywhere. Both operating systems read it; browsers never did, except Safari.`,
	},
	'.tiff': {
		enabled: false,
		mime: 'image/tiff',
		type: 'TIFF Image',
		title: 'Lossless image with transparency',
		imageNative: ['mac', 'windows'],
		imageWeb: ['mac'],
		contactSheet: 'canvas',
		about: `The full spelling of TIFF, the 1986 format of scanners, print and archives, which the Mac and Unix used without DOS's three-letter limit and which Apple's own software writes. Inside it is the same as a .tif: lossless, large, and built from tags, so a file may hold pages, layers or a compression not every program reads.`,
	},
	'.pict': {
		enabled: false,
		mime: 'image/x-pict',
		type: 'PICT Image',
		title: 'Image',
		imageNative: ['mac'],//if ImageIO still reads it, which recent versions of macOS have been letting go of; to be checked
		imageWeb: [],
		contactSheet: 'canvas',
		about: `Apple's QuickDraw picture, 1984, the Mac's own picture and clipboard format for the whole of the classic era. It holds drawing commands, so a file can be shapes and text as well as pixels, and it traveled onto PCs as .pct on floppies and clip art CDs. Mac OS X moved to PDF and Apple has since let it go, so newer Macs open it less and less, and no PC ever did without a converter.`,
	},
	'.pct': {
		enabled: false,
		mime: 'image/x-pict',
		type: 'PCT Image',
		title: 'Image',
		imageNative: ['mac'],//as for .pict, to be checked
		imageWeb: [],
		contactSheet: 'canvas',
		about: `The three-letter spelling of a PICT, Apple's classic Mac picture, used wherever a file name had to fit DOS, so it is the form a PICT took on a PC floppy or a clip art CD. Inside it is the same as a .pict, and it opens in the same few places.`,
	},
	'.iff': {
		enabled: false,
		mime: 'image/x-ilbm',
		type: 'IFF Image',
		title: 'Image',
		imageNative: [],//nothing native reads it; FFmpeg does
		imageWeb: [],
		contactSheet: 'chip',
		about: `Electronic Arts' Interchange File Format, 1985, made for the Amiga, and in its picture form, ILBM, the format of Deluxe Paint. The Amiga's pictures, its demo scene and much of the pixel art of 1980s and 1990s games passed through it. It holds a palette of up to 256 colors, or the Amiga's special modes with more. Almost nothing on a PC or a Mac opened it then, and only the specialist viewers do now.`,
	},
	'.lbm': {
		enabled: false,
		mime: 'image/x-ilbm',
		type: 'LBM Image',
		title: 'Image',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		about: `The DOS spelling of an ILBM picture, written by Deluxe Paint once Electronic Arts brought it to the PC in 1988. Deluxe Paint was the tool most game artists of the era drew in, so the backgrounds and sprites of the 1990s were .lbm files before they were anything else, and some collections keep them that way. Inside it is the same as an Amiga .iff, and it opens in the same few viewers.`,
	},
	'.wmf': {
		enabled: false,
		mime: 'image/wmf',
		type: 'WMF Image',
		title: 'Vector image',
		imageNative: [],//WIC does not read it, though Windows draws it everywhere else; ImageIO never has
		imageWeb: [],
		contactSheet: 'chip',
		about: `The Windows Metafile, 1990 with Windows 3.0: a recording of Windows' own drawing calls, so a picture is lines and shapes that scale, or a bitmap, or both. It was the format of clip art, the CDs of it and the gallery inside Office, and Office still pastes it. A flaw in how Windows drew it made it briefly famous in 2005. Office and its open source cousins open it; browsers and the Mac never did.`,
	},
	'.emf': {
		enabled: false,
		mime: 'image/emf',
		type: 'EMF Image',
		title: 'Vector image',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		about: `The Enhanced Metafile, 1993 with 32-bit Windows, the successor to .wmf: the same recording of Windows' drawing calls, with the precision and features the old format lacked. Office has pasted and saved drawings in it since, and it is the form clip art took from the mid-1990s on. It opens where .wmf does, in Office and its open source cousins, and in no browser or Mac.`,
	},
	'.psd': {
		enabled: false,
		mime: 'image/vnd.adobe.photoshop',
		type: 'PSD Image',
		title: 'Layered image with transparency',
		imageNative: ['mac'],//ImageIO reads the flattened picture Photoshop saves inside; WIC does not
		imageWeb: [],
		contactSheet: 'canvas',
		about: `Photoshop's own document, 1990, with the program. It holds the working picture: layers, masks, text still editable, adjustments not yet applied, so a file is many times a JPEG's size and only Photoshop shows all of it. Nearly every other program reads the flattened copy Photoshop stores beside the layers, which is how a Mac shows a preview. Designers work in it, and templates and mockups are shared in it.`,
	},
	'.heic': {
		enabled: false,
		mime: 'image/heic',
		type: 'HEIC Image',
		title: 'Image',
		imageNative: ['mac'],//not Windows, where WIC needs two extensions from the Microsoft Store, one of them paid
		imageWeb: ['mac'],//Safari shows it since 2023; Chromium does not
		contactSheet: 'canvas',
		about: `The High Efficiency Image Container, chosen by Apple for iPhone photos in 2017 and written by many Android phones since. Inside it is a still frame of HEVC video, about half the size of a JPEG at the same quality, with room for wide color, depth maps and bursts. That makes it the format of many recent phones' camera rolls, and the one a PC cannot open without two extensions from the Store, one of them paid, so phones convert to JPEG on the way out.`,
	},
	'.heif': {
		enabled: false,
		mime: 'image/heif',
		type: 'HEIF Image',
		title: 'Image',
		imageNative: ['mac'],//as for .heic; the sniff in thumbnail.rs answers heic for every brand of this container, so on the day this is switched on the flow's format name and the sniff's have to be made to agree
		imageWeb: ['mac'],
		contactSheet: 'canvas',
		about: `The High Efficiency Image Format under its container's own name, which some Android phones and converters write instead of .heic. Inside it is usually the same HEVC still a .heic holds, though the container can also carry AV1 or JPEG, and it opens wherever .heic does, which on a PC means the same two extensions from the Store.`,
	},
	'.dng': {
		enabled: false,
		mime: 'image/x-adobe-dng',
		type: 'DNG Image',
		title: 'Camera raw image',
		imageNative: ['mac'],//ImageIO reads raw files for the cameras Apple lists; Windows needs the Raw Image Extension from the Store
		imageWeb: [],
		contactSheet: 'canvas',
		about: `Adobe's Digital Negative, 2004, an open raw format built on TIFF and meant to end every camera maker having its own. It holds what the sensor recorded before a JPEG was made, so the exposure and colors are still to be decided. Leica, Pentax and now phones write it directly, iPhone and Android alike, and Adobe's converter turns any maker's raw into it. Photo software opens it; a plain viewer shows the small preview inside, if anything.`,
	},
	'.cr2': {
		enabled: false,
		mime: 'image/x-canon-cr2',
		type: 'CR2 Image',
		title: 'Camera raw image',
		imageNative: ['mac'],
		imageWeb: [],
		contactSheet: 'canvas',
		about: `Canon's raw file from 2004 to 2018, the sensor's own data with a JPEG preview beside it. Canon's digital SLRs of those years wrote it, and it needs photo software or the operating system's raw support to open, which lags each new camera by months. Canon moved to CR3 in 2018, which fewer programs read.`,
	},
	'.nef': {
		enabled: false,
		mime: 'image/x-nikon-nef',
		type: 'NEF Image',
		title: 'Camera raw image',
		imageNative: ['mac'],
		imageWeb: [],
		contactSheet: 'canvas',
		about: `Nikon's Electronic Format, the raw file of every Nikon digital camera since the D1 of 1999. Like every raw it is the sensor's data before any picture was made from it, with a preview inside, and it opens in photo software and in an operating system that knows the camera. The format changes a little with each model, so an old program may not read a new file.`,
	},
	'.arw': {
		enabled: false,
		mime: 'image/x-sony-arw',
		type: 'ARW Image',
		title: 'Camera raw image',
		imageNative: ['mac'],
		imageWeb: [],
		contactSheet: 'canvas',
		about: `Sony's raw file, from the Alpha cameras that began in 2006 when Sony bought Konica Minolta's camera business. Sony's mirrorless cameras made it one of the most common raw files of the 2010s. As with every raw, it is the sensor's data with a preview alongside, and it needs photo software or the operating system's raw support, which follows each new camera after a delay.`,
	},
	'.mp4': {
		enabled: false,
		mime: 'video/mp4',
		type: 'MP4 Video',
		title: 'Video with sound',
		imageNative: ['mac', 'windows'],//a frame the operating system picks, through AVFoundation on the Mac and the shell's own thumbnailer on Windows, which thumbnail.rs does not ask for yet
		imageWeb: [],//empty, since an img cannot show a video
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],//platforms where Rust plays the file through libmpv
		videoWeb: ['mac', 'windows'],//platforms where the web renderer plays the file in a video tag; not Linux, where WebKitGTK plays through whatever GStreamer plugins the machine has, which may not include H.264
		about: `MPEG-4 Part 14, standardized in 2001 and 2003 and built on Apple's QuickTime format, holding video, most often H.264, sound, most often AAC, and subtitles and chapters beside them. It became the one video file nearly everything writes and plays: phones, cameras, video sites and the web's own video tag, which every major browser plays in its H.264 form. The container is simple; the codecs inside carry patent licensing, and a file from a recent phone may hold H.265 video that older software cannot decode.`,
	},
	'.mov': {
		enabled: false,
		mime: 'video/quicktime',
		type: 'MOV Video',
		title: 'Video with sound',
		imageNative: ['mac', 'windows'],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: ['mac'],//the Mac alone: Chromium, inside WebView2 on Windows, does not officially play QuickTime, and WebKitGTK on Linux depends on the machine's GStreamer plugins
		about: `Apple's QuickTime movie, 1991, the container MP4 was later built from, and .qt in its earliest spelling. iPhones and many cameras record into it, most often H.264 or H.265 video with AAC sound, so inside it is usually what an MP4 holds under another name. Apple's software plays it anywhere; elsewhere it plays wherever the codec inside is supported, though not every program recognizes the name, and an old .mov can hold Cinepak or Sorenson video that little modern software still decodes.`,
	},
	'.avi': {
		enabled: false,
		mime: 'video/x-msvideo',
		type: 'AVI Video',
		title: 'Video with sound',
		imageNative: ['windows'],//the shell makes a frame of what Media Foundation can decode, which the codecs of the 1990s are not; libmpv would make one of any AVI
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],//no browser plays it
		about: `Microsoft's Audio Video Interleave, 1992, with Video for Windows: the first video most PC users ever played, a postage stamp of Cinepak, Indeo or Microsoft's own codec, playing unevenly from a CD-ROM. Around 2000 it became the container of DivX and Xvid, so an AVI from then is often a whole film. It is a box that can hold any codec at all, which is why a given AVI may play nowhere, and why players that carry every decoder with them exist.`,
	},
	'.mpg': {
		enabled: false,
		mime: 'video/mpeg',
		type: 'MPG Video',
		title: 'Video with sound',
		imageNative: ['windows'],//Media Foundation decodes MPEG-1; the Mac's AVFoundation plays it with the sound missing, and is left out
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `MPEG-1, 1993, in the three-letter spelling: the first video format that was truly a standard, so a file played on any machine with the decoder. It is the video of Video CD, whose .dat files are the same stream, of the first digital cameras that shot movies, and of the clips traded on CD-ROM and early websites, at 352 by 240. The same extension carries MPEG-2, the video of DVD and broadcast, from 1995. Nearly everything then and now plays it.`,
	},
	'.mpeg': {
		enabled: false,
		mime: 'video/mpeg',
		type: 'MPEG Video',
		title: 'Video with sound',
		imageNative: ['windows'],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `The full spelling of an MPEG-1 or MPEG-2 video, used where DOS's three-letter limit did not apply, on the Mac, Unix and the web. Inside it is the same as a .mpg: the standard video of Video CD, DVD and the 1990s internet, which nearly everything plays.`,
	},
	'.asf': {
		enabled: false,
		mime: 'video/x-ms-asf',
		type: 'ASF Video',
		title: 'Video with sound',
		imageNative: ['windows'],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `Microsoft's Advanced Systems Format, 1996, the container built for streaming over the internet of that day and the box every Windows Media file is in. An .asf is usually an early Windows Media video, from before Microsoft gave them the .wmv name in 1999, or a stream someone saved. Windows plays it at the factory; the Mac needed a plug-in, and everything else needs a decoder that knows Windows Media.`,
	},
	'.wmv': {
		enabled: false,
		mime: 'video/x-ms-wmv',
		type: 'WMV Video',
		title: 'Video with sound',
		imageNative: ['windows'],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `Windows Media Video, 1999, Microsoft's codec and container for the years when Windows Media Player came with the operating system and the web's video was a choice between it, RealPlayer and QuickTime. Windows Movie Maker wrote it, so many home videos of the 2000s are in it, and some files carry the copy protection of the early music and film stores. Windows still plays it; a Mac needs a converter or a player that brings its own decoder.`,
	},
	'.rm': {
		enabled: false,
		mime: 'video/vnd.rn-realvideo',
		type: 'RM Video',
		title: 'Video with sound',
		imageNative: [],//nothing native decodes RealVideo; FFmpeg does
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `RealMedia, from RealNetworks, 1997: RealVideo and RealAudio in one file, made for streaming over a modem, so a whole clip was a small blurry window and a lot of buffering. It was how the web watched anything before broadband, through RealPlayer. Nothing plays it today but the players that carry their own decoders.`,
	},
	'.rmvb': {
		enabled: false,
		mime: 'video/vnd.rn-realvideo',
		type: 'RMVB Video',
		title: 'Video with sound',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `RealMedia Variable Bitrate, the 2000s form of RealVideo, which spent its bits where the picture needed them and so fit a film on a CD. It became the standard for video traded across China and among anime fansub groups for most of that decade. It plays only in a player with its own decoder; the operating systems never had one.`,
	},
	'.flv': {
		enabled: false,
		mime: 'video/x-flv',
		type: 'FLV Video',
		title: 'Video with sound',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `Flash Video, Macromedia, 2002, and the file inside every Flash video player on the web. YouTube served its videos as .flv from 2005 until around 2010, so a video saved from YouTube in those years is usually one, in Sorenson Spark or On2's VP6 and later H.264. Flash's end in 2020 finished it. Players with their own decoders still open it; nothing else does.`,
	},
	'.m4v': {
		enabled: false,
		mime: 'video/x-m4v',
		type: 'M4V Video',
		title: 'Video with sound',
		imageNative: ['mac', 'windows'],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: ['mac'],
		about: `Apple's name for an MP4 of video, from the iTunes Store and the video iPod of 2005. Inside it is an ordinary MP4, H.264 with AAC sound, unless it was bought from the store, in which case it carries Apple's copy protection and plays only in Apple's software on an authorized machine. Ripping tools of the era, HandBrake among them, wrote the unprotected kind.`,
	},
	'.3gp': {
		enabled: false,
		mime: 'video/3gpp',
		type: '3GP Video',
		title: 'Video with sound',
		imageNative: ['mac', 'windows'],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: ['mac'],
		about: `The video of the phones before smartphones, from the 3GPP standards group around 2003: a tiny MP4 relative built for a flip phone's camera and its data plan, with H.263 or MPEG-4 video and AMR speech-quality sound. Most clips shot on a phone between about 2003 and 2010 are one, at 176 by 144. QuickTime and Windows play it, and everything else that plays MP4 usually does.`,
	},
	'.mkv': {
		enabled: false,
		mime: 'video/x-matroska',
		type: 'MKV Video',
		title: 'Video with sound',
		imageNative: ['windows'],//Windows 10 plays Matroska at the factory; AVFoundation does not
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: ['windows'],//Chromium plays it when the codecs inside are ones it has; WebKit never
		about: `Matroska, 2002, an open container that holds any video and sound at all, with several audio tracks, subtitles and chapters in the same file. That made it the format of anime fansubs and of the high-quality rips traded since, and it is the parent WebM was cut from. No video site sends it and Apple's players do not open it, but Windows has since 2015, and it is often the container of a collector's best copy of a film or a series.`,
	},
	'.webm': {
		enabled: false,
		mime: 'video/webm',
		type: 'WebM Video',//WebM keeps its own capitals, like WebP
		title: 'Video with sound',
		imageNative: ['windows'],//Windows 10 decodes VP8 and VP9 at the factory; AVFoundation does not
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: ['mac', 'windows'],//Safari plays it since 2021
		about: `Google's 2010 cut of Matroska for the web's video tag: VP8, VP9 or AV1 video with Vorbis or Opus sound, all free of patent fees. It is the video of the modern web's clips and reaction loops, the animated GIF's replacement, and the file Discord, Reddit and the imageboards trade in. Every browser plays it now, Safari last, in 2021.`,
	},
	'.ogv': {
		enabled: false,
		mime: 'video/ogg',
		type: 'OGV Video',
		title: 'Video with sound',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],//Chromium dropped Theora in 2024, and WebKit never had it
		about: `Ogg video, from the Xiph foundation, most often Theora, the free codec that Wikipedia and Firefox backed for the web's video tag around 2009. It lost to H.264 and then to WebM, and Chrome dropped it in 2024, so a file from that brief moment now needs a player with its own decoder. Rare, and mostly from Wikipedia downloads and free software demos.`,
	},
	'.vob': {
		enabled: false,
		mime: 'video/mpeg',
		type: 'VOB Video',
		title: 'Video with sound',
		imageNative: [],//Windows 10 decodes MPEG-2 only with an extension from the Store, free but not there by default, and the Mac does not
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `A DVD's Video Object, 1996: the MPEG-2 video of a disc with its Dolby sound, subtitles and menus, cut into pieces of a gigabyte. They are what a DVD looks like copied straight onto a drive, in a VIDEO_TS folder, and many were before ripping to a smaller file became the habit. A player that reads MPEG-2 plays one on its own; the menus only work from the folder.`,
	},
	'.m2ts': {
		enabled: false,
		mime: 'video/mp2t',
		type: 'M2TS Video',
		title: 'Video with sound',
		imageNative: ['windows'],//Media Foundation reads the transport stream; AVFoundation does not
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `The MPEG-2 transport stream as Blu-ray and the AVCHD camcorders of Sony and Panasonic write it, from 2006. It holds H.264 video at full high definition, so camcorder footage of the late 2000s and Blu-ray copies are in it. Windows plays it; the Mac's own software wants it converted first, which is what iMovie did on import, and players with their own decoders take it as it is.`,
	},
	'.divx': {
		enabled: false,
		mime: 'video/x-msvideo',
		type: 'DivX Video',//DivX keeps its own capitals, being a brand
		title: 'Video with sound',
		imageNative: ['windows'],//an AVI under another name, and Media Foundation decodes MPEG-4 Part 2
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `DivX's own name for an AVI holding its MPEG-4 video, from around 2000, when DivX began as a hacked Microsoft codec and became a company. Most DivX films kept the .avi name; the ones the company's tools wrote carry this one, and the DVD players of the mid-2000s with a DivX logo on the front play both. Inside it is an ordinary AVI, and it plays wherever the codec does, which today is nearly everywhere.`,
	},
	'.qt': {
		enabled: false,
		mime: 'video/quicktime',
		type: 'QT Video',
		title: 'Video with sound',
		imageNative: ['mac'],//AVFoundation, as for .mov; Windows does not know the name
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: ['mac'],
		about: `The earliest spelling of a QuickTime movie, from the Mac of 1991, before .mov became the habit. Inside it is the same as a .mov, and old CD-ROMs and Mac collections carry them, often holding Cinepak or Apple's own early codecs. Apple's software still opens it; elsewhere it depends on the codec inside.`,
	},
	'.mpe': {
		enabled: false,
		mime: 'video/mpeg',
		type: 'MPE Video',
		title: 'Video with sound',
		imageNative: ['windows'],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `The third spelling of an MPEG-1 or MPEG-2 video, rarer than .mpg and .mpeg and mostly written by 1990s Unix tools and web servers. Inside it is the same standard video, and everything that plays MPEG plays it once it recognizes the name, which not every program does.`,
	},
	'.ts': {
		enabled: false,//the same three letters name a TypeScript program, which is a reason to think before registering this one, on the day
		mime: 'video/mp2t',
		type: 'TS Video',
		title: 'Video with sound',
		imageNative: ['windows'],//Media Foundation reads the transport stream; AVFoundation does not
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `The MPEG-2 transport stream under its plain name: the format of digital television, so a file is a broadcast recorded off the air or from a satellite box, or a piece of a live internet stream saved to disk. Inside it is MPEG-2 or H.264 video. Windows plays it; the Mac's own software does not. The same three letters name a TypeScript program, so a programmer's folder holds .ts files that are not video at all.`,
	},
	'.mts': {
		enabled: false,
		mime: 'video/mp2t',
		type: 'MTS Video',
		title: 'Video with sound',
		imageNative: ['windows'],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `AVCHD's own name for its transport stream, the file a Sony or Panasonic camcorder wrote to its card from 2006 on. Copied through the maker's software it became .m2ts; copied by hand it stayed .mts, so footage copied straight from the card usually carries this one. Inside it is H.264 at full high definition, the same as an .m2ts, and it plays where that does.`,
	},
	'.dv': {
		enabled: false,
		mime: 'video/x-dv',
		type: 'DV Video',
		title: 'Video with sound',
		imageNative: ['mac'],//AVFoundation reads a DV stream; Media Foundation has a DV decoder too, to be checked
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `The raw stream of a MiniDV tape, the digital camcorder format of 1995 to about 2005, captured over FireWire at 13 gigabytes an hour, usually into an .avi or .mov but sometimes left bare. It is the home video of a decade, lightly compressed at the resolution of standard television, and a captured tape is one of these or its wrapped form. Both operating systems' video frameworks read it.`,
	},
	'.3g2': {
		enabled: false,
		mime: 'video/3gpp2',
		type: '3G2 Video',
		title: 'Video with sound',
		imageNative: ['mac', 'windows'],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: ['mac'],
		about: `The 3GPP2 twin of .3gp, for the phones on CDMA networks, Verizon and Sprint in the United States, from the same years around 2003 to 2010. Inside it is the same small MPEG-4 relative, and it plays wherever .3gp does.`,
	},
	'.f4v': {
		enabled: false,
		mime: 'video/mp4',
		type: 'F4V Video',
		title: 'Video with sound',
		imageNative: [],//an MP4 inside, but neither shell knows the name
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `Flash Video's second form, from 2007, when Adobe moved Flash from its own container to MP4 for H.264. A .f4v is an MP4 under a Flash name, so a saved video from a Flash player of the late 2000s may be one, and renaming it .mp4 usually makes it play anywhere. Players with their own decoders take it as it is.`,
	},
	'.ogm': {
		enabled: false,
		mime: 'video/ogg',
		type: 'OGM Video',
		title: 'Video with sound',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `Ogg Media, 2002, the Ogg container stretched to hold video, several audio tracks and subtitles at once, which nothing else did at the time. It was the fansub and rip format for a few years until Matroska, built for that job, replaced it. Rare now, and it plays only where a decoder knows the container.`,
	},
	'.nsv': {
		enabled: false,
		mime: 'video/x-nsv',
		type: 'NSV Video',
		title: 'Video with sound',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `Nullsoft Streaming Video, 2003, from the makers of Winamp, for the internet television and radio stations of Shoutcast. A saved stream from that world is one, in VP3 or VP6 video with MP3 sound. Winamp played it and almost nothing else did; the players that carry their own decoders are what open one now.`,
	},
	'.bik': {
		enabled: false,
		mime: 'video/vnd.radgamettools.bink',
		type: 'BIK Video',
		title: 'Video with sound',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `Bink Video, from RAD Game Tools, 1999, the cutscene format of thousands of PC and console games for two decades, from Baldur's Gate to Mass Effect. Its logo opened the game, and its files sit in the folders of many installed games. RAD's own player and the decoders FFmpeg carries open them; nothing that came with an operating system does.`,
	},
	'.wtv': {
		enabled: false,
		mime: 'video/x-ms-wtv',
		type: 'WTV Video',
		title: 'Video with sound',
		imageNative: ['windows'],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `Windows Recorded TV Show, 2008, what Windows Media Center recorded television into once a PC had a tuner card, replacing .dvr-ms. A file is a program off the air at several gigabytes an hour, often with copy protection. Media Center played it until Windows 10 retired Media Center; other players read the unprotected ones.`,
	},
	'.dvr-ms': {
		enabled: false,
		mime: 'video/x-ms-dvr',
		type: 'DVR-MS Video',
		title: 'Video with sound',
		imageNative: ['windows'],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `Microsoft Digital Video Recording, 2002, the first Windows Media Center recording format, from the years when a Media Center PC was the living room's video recorder. Inside it is MPEG-2 in an ASF wrapper, often with copy protection, and Windows played it as long as Media Center lasted. Players with their own decoders open the unprotected ones.`,
	},
	'.dat': {
		enabled: false,//and it stays out of registration even when video is on: countless programs call their own files .dat, so claiming the extension would claim files that are not video
		mime: 'video/mpeg',
		type: 'DAT Video',
		title: 'Video with sound',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'canvas',
		videoNative: ['mac', 'windows', 'linux'],
		videoWeb: [],
		about: `The video of a Video CD as the disc stores it, in an MPEGAV folder: MPEG-1 in a form nearly any player reads as an .mpg. Video CDs carried films and karaoke across Asia through the 1990s and 2000s, and a disc copied to a drive brings its .dat files along. The name is the trouble: countless programs call their own files .dat, so a .dat is video only when it came from a disc.`,
	},
	'.swf': {
		enabled: false,
		mime: 'application/x-shockwave-flash',
		type: 'SWF Animation',
		title: 'Animation with sound',
		imageNative: [],//nothing draws it: a Flash file is a program, not a picture or a video
		imageWeb: [],
		contactSheet: 'chip',//here so a folder of them names itself
		about: `Macromedia's Shockwave Flash, 1996, the animation and game format of the web from the late 1990s until the 2010s: Newgrounds, the cartoons and games passed around by email, and the intro pages of the era's corporate sites. A file is a program with drawings and sound in it, not a video, so only a Flash player runs it, and Adobe ended Flash in 2020. Emulators such as Ruffle run most of them now; fuji names them and does no more.`,
	},
	'.wav': {
		enabled: false,
		mime: 'audio/wav',
		type: 'WAV Audio',
		title: 'Lossless audio',
		imageNative: [],//audio has no picture to make, so an audio file is always a chip
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],//platforms where Rust plays the file through libmpv, which carries its own decoders and drives the machine's audio output itself
		audioWeb: ['mac', 'windows'],//platforms where the web renderer plays the file in an audio tag; not Linux, for the reason the videos give
		about: `Microsoft and IBM's Waveform file, 1991 with Windows 3.1, holding sound as the plain samples a CD does. It is Windows' own sound: the chimes and dings, the first step of a CD rip, the recording studio's working file, and the sound effects of a decade of games. Ten megabytes a minute, so it was never for trading. Everything opens it.`,
	},
	'.aiff': {
		enabled: false,
		mime: 'audio/aiff',
		type: 'AIFF Audio',
		title: 'Lossless audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: ['mac'],
		about: `Apple's Audio Interchange File Format, 1988, built on Electronic Arts' IFF, and the Mac's plain sound file three years before WAV: samples as recorded, large, and lossless. It is what Mac music software wrote and what iTunes rips to when asked for lossless, so it is common in music made or ripped on a Mac. Every serious audio program opens it, and Windows has since Windows 7.`,
	},
	'.aif': {
		enabled: false,
		mime: 'audio/aiff',
		type: 'AIF Audio',
		title: 'Lossless audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: ['mac'],
		about: `The three-letter spelling of AIFF, Apple's lossless sound file of 1988, used wherever a name had to fit DOS or a Mac program simply preferred it. Inside it is the same as an .aiff.`,
	},
	'.mid': {
		enabled: false,
		mime: 'audio/midi',
		type: 'MID Audio',
		title: 'Music as notes',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],//libmpv plays it only where its FFmpeg was built with a synthesizer, which the usual builds are not; the operating systems have one, and asking them is a route of its own, so this list is intent rather than fact
		audioWeb: [],//no browser plays it
		about: `A Standard MIDI File, 1991, holding no sound at all but the notes, their timing and which instrument plays each, so a song is a few kilobytes and sounds like whatever synthesizer plays it, a Sound Blaster's tinny FM chip or a Roland card's real samples. It was the music of 1990s games and of web pages that played a tune when they opened. Windows still plays one with its built-in synthesizer.`,
	},
	'.midi': {
		enabled: false,
		mime: 'audio/midi',
		type: 'MIDI Audio',
		title: 'Music as notes',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],//as for .mid: intent, resting on a synthesizer fuji does not have yet
		audioWeb: [],
		about: `The four-letter spelling of a Standard MIDI File, used on the Mac, on Unix and by most modern software, where DOS's three-letter limit never applied. Inside it is the same as a .mid: notes and their timing rather than sound, played by whatever synthesizer is at hand.`,
	},
	'.mod': {//also the name JVC and Panasonic camcorders gave their MPEG-2 clips in the mid-2000s, a second meaning one key cannot hold; this entry is the tracker module
		enabled: false,
		mime: 'audio/x-mod',
		type: 'MOD Audio',
		title: 'Music as samples and patterns',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],//through libmpv where its FFmpeg was built with libopenmpt, to be checked on the day
		audioWeb: [],
		about: `The module, from Ultimate Soundtracker on the Amiga, 1987: a song as a set of recorded samples plus the patterns that play them, four channels at a time, so it sounds the same on every machine and fits on a floppy. It was the music of the demo scene, of the BBS file areas, and of games on the Amiga and then the PC. Trackers and a few players open it; nothing that came with an operating system ever did.`,
	},
	'.s3m': {
		enabled: false,
		mime: 'audio/x-s3m',
		type: 'S3M Audio',
		title: 'Music as samples and patterns',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],
		about: `Scream Tracker 3's module, 1994, from Future Crew, the Finnish group behind the demos that defined the PC scene. It gave the PC what the Amiga had: samples and patterns, now with more channels and the Gravis Ultrasound to play them on. The music of the DOS demo scene and of the BBS era's file areas is in this and in .xm.`,
	},
	'.xm': {
		enabled: false,
		mime: 'audio/x-xm',
		type: 'XM Audio',
		title: 'Music as samples and patterns',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],
		about: `FastTracker 2's extended module, 1994, from Triton, another Scandinavian demo group: up to 32 channels, instruments with envelopes rather than bare samples, and the tracker most of the scene moved to. More tracker music of the middle and late 1990s is in this format than any other, and the games that used trackers, Unreal among them, used it.`,
	},
	'.it': {
		enabled: false,
		mime: 'audio/x-it',
		type: 'IT Audio',
		title: 'Music as samples and patterns',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],
		about: `Impulse Tracker's module, 1995, the last and most capable of the great DOS trackers, with 64 channels, stereo samples and effects the others lacked. It carried the scene into the 2000s and is the format the tracker world still writes by preference, so a collection of scene music runs from .mod through .s3m and .xm to this.`,
	},
	'.mp3': {
		enabled: false,
		mime: 'audio/mpeg',
		type: 'MP3 Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: ['mac', 'windows'],
		about: `MPEG-1 Audio Layer III, from Fraunhofer, 1993: a song at a tenth of a CD's size with most of what the ear hears, which is what made music a file. Winamp in 1997, Napster in 1999 and the iPod in 2001 followed from it, and it has been the common form of a music file since. Its patents ran out in 2017. Everything plays it, and the 128 kilobit files of the Napster years show their age.`,
	},
	'.ra': {
		enabled: false,
		mime: 'audio/vnd.rn-realaudio',
		type: 'RA Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],//FFmpeg decodes the common RealAudio codecs
		audioWeb: [],
		about: `RealAudio, 1995, the first sound that streamed over a modem: radio and speeches at 14.4 kilobits, thin and muffled. It was the internet's audio for the few years before MP3, and a saved clip from a 1990s radio site is one. Nothing plays it now but a player that carries its own decoders.`,
	},
	'.wma': {
		enabled: false,
		mime: 'audio/x-ms-wma',
		type: 'WMA Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],
		about: `Windows Media Audio, 1999, Microsoft's answer to MP3 and the format Windows Media Player ripped CDs to unless told otherwise, so CDs ripped on Windows in the early 2000s are often in it whether or not the user meant to choose it. Some files carry the copy protection of the music stores of the time, and no longer play anywhere. Windows still plays the rest; a Mac and the web never did.`,
	},
	'.ogg': {
		enabled: false,
		mime: 'audio/ogg',
		type: 'OGG Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: ['windows'],//Chromium plays Vorbis in Ogg; WebKit does not play the Ogg container
		about: `Ogg Vorbis, from the Xiph foundation, 2000, made when Fraunhofer began charging for MP3 encoders: free of patents and better than MP3 at the same size. It never displaced MP3 because the iPod would not play it, but it became the sound of games, Unreal Tournament and Minecraft among them, of Wikipedia, and inside Spotify's streams. Most players open it; Apple's do not.`,
	},
	'.m4a': {
		enabled: false,
		mime: 'audio/mp4',
		type: 'M4A Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: ['mac', 'windows'],
		about: `AAC sound in an MP4 container, under the name Apple gave it in 2003 with the iTunes Music Store. iTunes rips to it and the store sold it, protected files as .m4p, so an iTunes library is largely made of them. AAC is MP3's successor and sounds better at the same size. Everything modern plays it.`,
	},
	'.aac': {
		enabled: false,
		mime: 'audio/aac',
		type: 'AAC Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: ['mac', 'windows'],
		about: `Advanced Audio Coding, 1997, the MPEG standard that succeeded MP3 and the sound inside MP4 video, iTunes and YouTube. As a bare .aac it is the stream without its container, written by some rippers and radio recorders; the same sound in a box is an .m4a. Most players open it.`,
	},
	'.flac': {
		enabled: false,
		mime: 'audio/flac',
		type: 'FLAC Audio',
		title: 'Lossless audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: ['mac', 'windows'],
		about: `The Free Lossless Audio Codec, 2001, which packs a CD's sound to about half its size with every bit intact. It is the collector's format: the exact rip, the Bandcamp download, the concert recording traded among fans. For years only the dedicated players opened it; now nearly everything does, and the browsers and Apple's software have since 2017.`,
	},
	'.opus': {
		enabled: false,
		mime: 'audio/opus',
		type: 'Opus Audio',//Opus keeps its capital, being a name and not letters
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: ['windows'],//Chromium plays it; WebKit plays Opus only inside its own CAF container
		about: `Opus, 2012, from Xiph and the internet's standards body, the codec of speech and music online now: voice notes, Discord, video calls, and the sound under YouTube's video. It is small and good at every bitrate, and usually travels inside an .ogg or .webm; a file named .opus is Ogg. Every modern player opens it.`,
	},
	'.mp2': {
		enabled: false,
		mime: 'audio/mpeg',
		type: 'MP2 Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],//neither engine reliably plays a bare Layer II stream
		about: `MPEG-1 Audio Layer II, 1993, the sound of Video CD, DVD and digital radio and television, from the same standard as MP3 but simpler. A bare .mp2 is a track pulled from one of those, or a broadcast recording. Most players open it; the web never adopted it.`,
	},
	'.ac3': {
		enabled: false,
		mime: 'audio/ac3',
		type: 'AC3 Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],
		about: `Dolby Digital, as Dolby's AC-3, in cinemas from 1991 and on DVD from 1997: the surround sound of every DVD and most Blu-ray discs. A bare .ac3 is a soundtrack pulled from a disc, kept beside the video or for a home theater's receiver. Players with their own decoders open it; the operating systems play it inside a video and rarely alone.`,
	},
	'.dts': {
		enabled: false,
		mime: 'audio/vnd.dts',
		type: 'DTS Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],
		about: `Digital Theater Systems' surround sound, 1993, the alternative to Dolby on DVD and Blu-ray, usually at higher bitrates. A bare .dts is a disc's soundtrack extracted, and a few music albums were released as DTS on CD. It needs a decoder, which the players carrying their own have and the operating systems mostly do not.`,
	},
	'.ape': {
		enabled: false,
		mime: 'audio/x-ape',
		type: 'APE Audio',
		title: 'Lossless audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],
		about: `Monkey's Audio, 2000, lossless like FLAC and a little smaller, and slower to decode. It was the format of the lossless music trading circles before FLAC won, and a whole album is often one .ape with a .cue beside it saying where the tracks begin. Foobar2000 and the players with their own decoders open it; nothing from an operating system does.`,
	},
	'.wv': {
		enabled: false,
		mime: 'audio/x-wavpack',
		type: 'WV Audio',
		title: 'Lossless audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],
		about: `WavPack, 1998, an open lossless format from before FLAC, with a hybrid mode that splits a song into a small lossy file and a correction file that restores the rest. It never had FLAC's following, but a share of the lossless rips traded in the 2000s are in it, and the dedicated players all open it.`,
	},
	'.m4p': {
		enabled: false,
		mime: 'audio/mp4',
		type: 'M4P Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: [],//nothing outside Apple's software plays a FairPlay file, so no route; here so a folder of iTunes purchases names itself
		audioWeb: [],
		about: `A protected iTunes Store purchase, 2003 to 2009: an .m4a with Apple's FairPlay copy protection, playable only in iTunes on a computer authorized to the account that bought it. The store dropped the protection in 2009 and offered to upgrade old purchases, but a purchase never upgraded stays protected, and nothing else opens it.`,
	},
	'.amr': {
		enabled: false,
		mime: 'audio/amr',
		type: 'AMR Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],
		about: `Adaptive Multi-Rate, the speech codec of GSM phones from 1999, and the file a phone of the 2000s saved a voice memo or a recorded call as. It holds speech and little else, at telephone quality, in files small enough to send over the networks of the time. Phones and the players with their own decoders play it, and QuickTime does as well.`,
	},
	'.au': {
		enabled: false,
		mime: 'audio/basic',
		type: 'AU Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],
		about: `Sun's audio file, from the late 1980s on its Unix workstations and NeXT's, and the sound of the early web: the first browsers and Java's first applets played .au before anything else, so a 1990s web page's sound effect was one. Usually 8-bit samples at telephone quality. Most players still open it; nothing writes it now.`,
	},
	'.snd': {
		enabled: false,
		mime: 'audio/basic',
		type: 'SND Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],
		about: `NeXT's name for the sound file Sun called .au, from the late 1980s, since the two companies' formats were one. Inside it is the same telephone-quality sound, and it opens where .au does. Other programs used the name loosely for sounds of their own, so not every .snd is one.`,
	},
	'.voc': {
		enabled: false,
		mime: 'audio/x-voc',
		type: 'VOC Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],
		about: `Creative Voice, 1989, the sound file of the Sound Blaster, the card that gave the PC sound. DOS games and the Sound Blaster's own tools recorded and played it, so it dates from the start of PC multimedia, alongside the first .wav files. Windows made WAV the standard and .voc faded by the mid-1990s, but the players with their own decoders still open it.`,
	},
	'.669': {
		enabled: false,
		mime: 'audio/x-669',
		type: '669 Audio',
		title: 'Music as samples and patterns',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: [],
		about: `Composer 669's module, 1992, one of the first PC trackers, written for the AdLib and Sound Blaster cards before Scream Tracker. Its eight channels and few effects show its age, and the scene moved on within two years, but the earliest PC demo and BBS music is in it. Tracker players open it.`,
	},
	'.mka': {
		enabled: false,
		mime: 'audio/x-matroska',
		type: 'MKA Audio',
		title: 'Audio',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],
		audioWeb: ['windows'],//Chromium reads Matroska when the codec inside is one it has
		about: `Matroska audio, the same 2002 container as .mkv holding sound alone: a whole album in one file with chapters for tracks, or a film's soundtrack in several languages. It is a collector's format rather than a common one, and the players that open .mkv open it.`,
	},
	'.rmi': {
		enabled: false,
		mime: 'audio/midi',
		type: 'RMI Audio',
		title: 'Music as notes',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		audioNative: ['mac', 'windows', 'linux'],//as for .mid: intent, resting on a synthesizer fuji does not have yet
		audioWeb: [],
		about: `A MIDI file wrapped in Microsoft's RIFF, the same wrapper WAV uses, from Windows 3.1 in 1992. Windows' own MIDI tools wrote it and Media Player plays it, and inside is an ordinary Standard MIDI File, so a player that knows the wrapper gets the notes out. Rare beside .mid.`,
	},
	'.m3u': {
		enabled: false,
		mime: 'audio/x-mpegurl',
		type: 'M3U Playlist',
		title: 'Playlist',
		imageNative: [],//a playlist, a cue sheet and a subtitle file are text beside the media, and fuji names them and does no more
		imageWeb: [],
		contactSheet: 'chip',
		about: `The playlist of Winamp, 1997: a text file listing the paths of songs, one per line, in the order to play them. Every music player since has read it, internet radio stations hand one out to start a stream, and .m3u8 is the same file in UTF-8, which streaming video later borrowed. Playlists from the MP3 years are in it, pointing at files that may since have moved.`,
	},
	'.m3u8': {
		enabled: false,
		mime: 'audio/x-mpegurl',
		type: 'M3U8 Playlist',
		title: 'Playlist',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		about: `An .m3u written in UTF-8, so a song with an accent in its name is found; the 8 names the encoding. Music players began writing it in the 2000s, and Apple's HTTP Live Streaming borrowed it in 2009 as the index of a video stream, so a .m3u8 today may be a playlist of songs or the recipe of a stream. Inside it is the same text as an .m3u.`,
	},
	'.pls': {
		enabled: false,
		mime: 'audio/x-scpls',
		type: 'PLS Playlist',
		title: 'Playlist',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		about: `The Shoutcast playlist, from Winamp and its internet radio of 1998: a small text file in Windows' INI style naming a station's stream or a set of songs. Clicking one on a radio site opened it in Winamp, and one saved from those years names a stream that may no longer exist.`,
	},
	'.cue': {
		enabled: false,
		mime: 'application/x-cue',
		type: 'CUE Sheet',
		title: 'Track list for a disc image',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		about: `A cue sheet, from the CD burning program CDRWIN in the 1990s: a text file saying where each track starts in a single file holding a whole disc, and what the disc and its tracks were called. It is how a CD ripped as one .ape, .flac or .wav still knows its tracks, and how one is burned back exactly, so it sits beside those files in lossless collections.`,
	},
	'.xspf': {
		enabled: false,
		mime: 'application/xspf+xml',
		type: 'XSPF Playlist',
		title: 'Playlist',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		about: `The XML Shareable Playlist Format, 2006, from the Xiph foundation, meant to be the open playlist that named songs by more than a path. VLC adopted it as its own, and a playlist saved from VLC is one. Few other players read it.`,
	},
	'.srt': {
		enabled: false,
		mime: 'application/x-subrip',
		type: 'SRT Subtitles',
		title: 'Subtitles',
		imageNative: [],
		imageWeb: [],
		contactSheet: 'chip',
		about: `SubRip's subtitle file, from the program of that name around 2000 that read subtitles off DVDs: plain text, each line with the time it appears and disappears. It became the one subtitle format everything reads, and a downloaded film or series comes with a .srt beside it, named to match, which players pick up on their own.`,
	},
}

export const fileTypesEnabled = Object.fromEntries(Object.entries(fileTypes).filter(([extension, entry]) => entry.enabled))//the entries fuji acts on today, which is what everything but the settings reads
